version: "0.2"
import:
  - "@joshuafolkken/kit/cspell/sveltekit"
words:
  - docstrings
  - gameover
  - languagetool
  - metalness
  - METALNESS
  - nipplejs
  - oncreate
  - Orbitron
  - raycaster
  - Raycaster
  - shellcheck
  - Stylesheet
  - sveltekit
  - threlte
  - trycloudflare
ignorePaths: []
