version: '0.2'
import:
  - '@joshuafolkken/kit/cspell/sveltekit'
words:
  - docstrings
  - languagetool
  - shellcheck
  - Stylesheet
  - sveltekit
  - threlte
  - nipplejs
  - oncreate
  - gameover
  - raycaster
  - Raycaster
ignorePaths: []
