version: "0.2"
import:
  - "@joshuafolkken/kit/cspell/sveltekit"
ignorePaths:
  - "**/credits-config.ts"
words:
  - Baer
  - coeff
  - COEFF
  - BAER
  - Boisclair
  - BOISCLAIR
  - codeman
  - CODEMAN
  - docstrings
  - gameover
  - languagetool
  - McInerney
  - MCINERNEY
  - metalness
  - METALNESS
  - mrdoob
  - MRDOOB
  - nipplejs
  - Pixabay
  - PIXABAY
  - oncreate
  - Orbitron
  - raycaster
  - Raycaster
  - shellcheck
  - Stylesheet
  - sveltekit
  - tailwindlabs
  - TAILWINDLABS
  - threlte
  - trycloudflare
  - unstub
  - yoannmoinet
  - YOANNMOINET
